[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[[test]]
name = "main"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cucumber = "0.20.2"
tokio = { version = "1", features = ["full"] }
