name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.41.0

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose